project:
  type: website

website:
  title: "Jesse DeBolt's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - Resume.qmd
      - icon: linkedin
        href: www.linkedin.com/in/jessedebolt
      - icon: git
        href: https://github.com/jessedebolt/Portfolio_project

format:
  html:
    theme: superhero
    css: styles.css
    toc: true



