project:
  type: website

website:
  title: "Jesse DeBolt's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - Resume.qmd
      - icon: linkedin
        href: www.linkedin.com/in/jessedebolt
<<<<<<< HEAD
      - icon: github
=======
      - icon: git
>>>>>>> 3c1c13b47e55a156cd8415bc2f5866779e00e272
        href: https://github.com/jessedebolt/Portfolio_project

format:
  html:
    theme: superhero
    css: styles.css
    toc: true



