project:
  type: website

website:
  title: "Jesse DeBolt's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - Resume.qmd

format:
  html:
    theme: superhero
    css: styles.css
    toc: true



