project:
  type: website

website:
  title: "Jesse DeBolt's Portfolio"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
    right:
      - Resume.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/jessedebolt
      - icon: github
        href: https://github.com/jessedebolt/Portfolio_project

  page-footer:
    left: "©2021, Jesse A. DeBolt" 
    right: "This is a Quarto website. To learn more visit [https://quarto.org/docs/websites](https://quarto.org/docs/websites)"
    border: false

    
format:
  html:
    theme: superhero
    css: styles.css
    toc: true
