---
title: "About"
---

Jesse is an accomplished engineer and aspiring data scientist with a passion for process improvement and data-driven insights. With a keen eye for identifying optimization opportunities and a knack for visualizing complex concepts, he has honed his skills in data analysis, visualization, and data wrangling during his pursuit of a Master of Science degree in data science.

Throughout his career, Jesse has demonstrated exceptional leadership and project management abilities. He has successfully managed diverse teams in multiple disciplines across different entities, fostering collaboration and championing continuous improvement projects. His expertise was instrumental in developing a cost system configurator and costing database tool, revolutionizing product selection and cost estimation accuracy.

An advocate for cross-functional collaboration, Jesse seamlessly collaborates with internal departments and external suppliers to ensure compliance with design and quality requirements, while meeting production milestones. He is adept at maintaining key performance indicators (KPIs) and consistently delivers valuable insights to management through accurate reporting.

In his quest for operational excellence, Jesse has engineered innovative solutions that have yielded remarkable results. Notably, his leadership in developing a routing generator tool significantly reduced shop floor routing generation lead-time, resulting in substantial cost savings. Leveraging his expertise in methodologies such as Value Stream Mapping, 5S, Ishikawa, and A3 (PDCA), he has consistently driven continuous improvement initiatives that have had a lasting impact.

Beyond his professional achievements, Jesse is a dedicated family person and an avid outdoor enthusiast. He enjoys spending time with his spouse and three sons, embarking on camping and hiking adventures, and taking on home remodel and improvement projects. Additionally, he is deeply committed to raising mental health awareness and promoting advocacy. Jesse recognizes the intersection of data science and mental health, and he is keen on leveraging his skills and knowledge to contribute to research and initiatives in this field.

With a Bachelor of Science degree in Manufacturing Engineering from the Oregon Institute of Technology, Jesse has a solid educational foundation. His technical skills encompass a wide range of tools and platforms, including proficiency in MS Office Products, SAP ERP system, and R programming. He has a keen eye for data visualization and possesses the ability to derive meaningful insights from complex datasets.

Driven by a genuine passion for mentoring others, both professionally and personally, Jesse finds joy in sharing his knowledge and experiences with others. His dedication to fostering growth and development has earned him a reputation as a reliable mentor and a source of guidance.

In summary, Jesse is an experienced engineer, a dedicated student of data science, and a natural problem-solver. He brings a unique blend of technical prowess, leadership skills, and a down-to-earth personality to every endeavor. With an unwavering commitment to continuous improvement and a drive to make a positive impact, Jesse is poised to excel in the field of data science and contribute to shaping a data-driven future, in relation to the manufacturing field as well as mental health awareness, research, and advocacy.


